# @package _global_
defaults:
- _self_
- method: sum

model: ViT-B-32
num_tasks: 8
specify_lambda: None

DATASETS: ''
DATASETS_VAL: ''

# utilities
cache_dir: None
world_size: 1
port: 12355
n_eval_points: 31
device: "cuda"
batch_size: 32
data_location: "/workspace/data"  # 여기서 변경
model_location: "/workspace/weight/checkpoints"  # 여기서 변경
save_subfolder: ""

# compatibility coding
TA_mode: true
save_weight: false
do_k_serach: false

wandb:
  project: task-vectors
  mode: online
  group: ${model}

hydra:
  run:
    dir: ./logs/${model}/${method.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
